# Question 1

Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
import numpy as np
arr = np.arange(2,50,3)
print (arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2

Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [3]:
import numpy as np

list1 = []
list2 = []

for i in range (5) :
    a = int(input("Enter value for list 1 :-"))
    list1.append(a)

for i in range (5) :
    b = int(input("Enter value for list 2 :-"))
    list2.append(b)

arr1 = np.array(list1)
arr2 = np.array(list2)

arr = np.concatenate((arr1,arr2))
print("Concatenated array :-",arr)

sorting = np.sort(arr)
print("Sorted array :-",sorting)

Enter value for list 1 :-10
Enter value for list 1 :-9
Enter value for list 1 :-8
Enter value for list 1 :-7
Enter value for list 1 :-6
Enter value for list 2 :-5
Enter value for list 2 :-4
Enter value for list 2 :-3
Enter value for list 2 :-2
Enter value for list 2 :-1
Concatenated array :- [10  9  8  7  6  5  4  3  2  1]
Sorted array :- [ 1  2  3  4  5  6  7  8  9 10]


# Question 3

Write a code snippet to find the dimensions of a ndarray and its size.

In [5]:
import numpy as np

arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])

print("Dimension of array :-", arr.ndim)
print("Size of array :-", arr.size)

Dimension of array :- 2
Size of array :- 9


# Question 4

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

In [16]:
import numpy as np

arr = np.arange(10)
print("Shape of array :-", arr.shape)

print("\n---np.newaxis snippet---")

row_arr = arr[np.newaxis , :]
print("Shape of 2D array in row major :-", row_arr.shape)

column_arr = arr[:, np.newaxis]
print("Shape of 2D array in column major :-", column_arr.shape)

print("\n---np.expand_dims snippet---")

row_arr1 = np.expand_dims(arr, axis=0)
print("Shape of 2D array in row major :-", row_arr1.shape)

column_arr1 = np.expand_dims(arr, axis=1)
print("Shape of 2D array in column major :-", column_arr1.shape)


Shape of array :- (10,)

---np.newaxis snippet---
Shape of 2D array in row major :- (1, 10)
Shape of 2D array in column major :- (10, 1)

---np.expand_dims snippet---
Shape of 2D array in row major :- (1, 10)
Shape of 2D array in column major :- (10, 1)


# Question 5

Consider two square numpy arrays. Stack them vertically and horizontally.

In [24]:
import numpy as np

arr1 = np.square([1,2,3,4,5])
arr2 = np.square([6,7,8,9,10])

print("Vertical Stack :-\n", np.vstack((arr1, arr2)))
print("\nHorizontal Stack :-\n", np.hstack((arr1, arr2)))

Vertical Stack :-
 [[  1   4   9  16  25]
 [ 36  49  64  81 100]]

Horizontal Stack :-
 [  1   4   9  16  25  36  49  64  81 100]


# Question 6

How to get unique items and counts of unique items?

numpy.unique

This function returns an array of unique elements in the input array. The function can be able to return a tuple of array of unique vales and an array of associated indices.

In [27]:
import numpy as np

arr = np.array([1, 1, 2, 3, 3, 3, 4, 4, 1])

(unique, counts) = np.unique(arr, return_counts=True)
frequencies = np.asarray((unique, counts)).T
print (frequencies)

[[1 3]
 [2 1]
 [3 3]
 [4 2]]
